# Generated by Django 4.2.1 on 2023-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=65)),
                ('lastName', models.CharField(max_length=65)),
                ('email', models.CharField(max_length=80)),
                ('interests', models.CharField(max_length=255)),
            ],
        ),
    ]
